-- Add new enum values to MessageType
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'TEXT';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'IMAGE';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'FILE';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'AUDIO';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'VIDEO';

-- Create new enums
CREATE TYPE "ConversationType" AS ENUM ('DIRECT', 'GROUP', 'APPLICATION_RELATED');
CREATE TYPE "ParticipantRole" AS ENUM ('ADMIN', 'MODERATOR', 'MEMBER');